name: VS Code Tunnel

on:
  workflow_dispatch: # Allows you to trigger this workflow manually

jobs:
  vscode-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract VS Code CLI
        run: |
          curl -sL "https://code.visualstudio.com/sha/download?build=stable&os=cli-linux-x64" --output vscode_cli.tar.gz
          tar -xf vscode_cli.tar.gz
          rm vscode_cli.tar.gz

      - name: Start VS Code Tunnel
        run: |
          # This command will output an authentication code in the GitHub Actions logs.
          # You will need to view the workflow logs, copy the code, and enter it at https://github.com/login/device
          ./code tunnel --accept-server-license-terms
